
- name: create consul directory
  file: >
    state=directory
    path={{ item }}
  with_items:
    - /data/consul/data
    - /data/consul/config
    - "{{ logs_dir }}"
  tags: [consul]


- name: check archive stat
  stat: path={{ consul_download_folder }}/{{ consul_archive }}
  register: consul_archive_stat

- name: download consul
  get_url: >
    url={{consul_download}}
    dest={{consul_download_folder}}
    url_username={{ consul_download_username }}
    url_password={{ consul_download_password }}
  register: consul_was_downloaded
  when: consul_archive_stat.stat.exists == False
  tags: [consul]

- name: copy and unpack
  unarchive: >
    src={{ consul_download_folder }}/{{ consul_archive }}
    dest={{ consul_move_to }}
    remote_src=yes
  when: consul_was_downloaded|changed
  tags: [consul]

#- name: Files are copied
#  copy:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    mode: "{{ item.mode }}"
#  with_items: files
#  tags: [consul]

- name: Is running
  shell: "nohup consul agent {{ consul_extra }} \
    -data-dir /data/consul/data \
    -config-dir /data/consul/config \
    -node={{ ansible_hostname }} \
    -bind={{ ip }} \
    -client=0.0.0.0 \
    >{{ logs_dir }}/consul.log 2>&1 &"
  tags: [consul]

- name: Has joined
  shell: consul join {{ consul_server_ip }}
  when: consul_server_ip is defined
  tags: [consul]